version: "3"

services:
  vue:
    container_name: vue_container
    build: ./frontend/vue
    volumes:
      - ./frontend/vue:/app
    ports:
      - "8080:8080"
    networks:
      - app_network
    restart: on-failure
    depends_on:
      - django
    working_dir: /app
    command: bash -c "npm install && npm run serve"

  django:
    build: ./backend/django/
    container_name: django_container
    volumes:
      - ./backend/django:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app_network
    command: "python3 manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - app_network

networks:
  app_network:
