version: '3.3'

services:
  web:
    build: ./backend/django3/
    container_name: django_container2
    volumes:
      - ./backend/django3:/app
    ports:
      - "8000:8000"
    command: "python3 manage.py runserver 0.0.0.0:8000"
    
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_container 
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust
