# Generated by Django 3.0.2 on 2021-02-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0018_auto_20210208_1032'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='exercices',
            field=models.ManyToManyField(blank=True, to='exercice.Exercice'),
        ),
    ]
