# Generated by Django 2.1.1 on 2020-12-25 10:52

from django.db import migrations, models
import modules.users.validations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180917_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CPF',
            field=models.CharField(max_length=12, unique=True, validators=[modules.users.validations.validate_cpf, modules.users.validations.validate_cpf_length]),
        ),
    ]
