# Generated by Django 3.0.2 on 2021-01-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coche_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='propietario',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='api.Employee'),
        ),
    ]
